path: /home/darklord/Downloads/hand-keypoints/
train: train/images
val: val/images

kpt_shape: [21, 3]
flip_idx:
  [0, 1, 2, 4, 3, 10, 11, 12, 13, 14, 5, 6, 7, 8, 9, 15, 16, 17, 18, 19, 20]
  
names:
  0: hand